### ISSUE TITLE
第二次开局时读取INI阶段内存使用异常上涨

### ISSUE THREAD

**Issue by ChrisLv-CN** [Xkein/DPExtension-Dionysus#2]
不使用DTA，使用原版游戏，开始一局后退出，重新开局，内存占用在读取INI阶段开始飙升，此时载入进度条停滞，直至第一局游戏的一倍左右，随后进度往前走，进入游戏，内存占用骚有回落。每次重开局，都可以观察到相同的情况。

**Comment by Xkein** [comment]
INI读取已重写，Ext类现可直接引用（抛弃ExtensionReference）
